jobs:
# Replace params / app_name with your heroku app name
- name: ci
  plan:
  - aggregate:
    - get: heroku-pipeline-app
      trigger: true
    - get: heroku-pipeline-infra
  - task: sync_heroku
    file: heroku-pipeline-infra/concourse/heroku/heroku_sync.yml
    input_mapping: {source: heroku-pipeline-app}
    params:
      app_name: ((heroku_app_name))
      heroku_email: ((heroku_email))
      heroku_api_token: ((heroku_api_key))

- name: infra
  plan:
  - aggregate:
    - get: heroku-pipeline-infra
      trigger: true
  - task: apply
    file: heroku-pipeline-infra/concourse/terraform/task.yml
    input_mapping: {source: heroku-pipeline-infra}
    params:
      github_token: ((github_token))
      heroku_api_key: ((heroku_api_key))
      command: apply
      directories: |
          terraform

#  The with-state is an output from the apply task. It's a git repo with
#  An updated terraform tfstate file.

  - put: heroku-pipeline-infra
    params:
      repository: with-state
      rebase: true

resources:

# Replace with your own repository
- name: heroku-pipeline-app
  type: git
  source:
      uri: git@github.com:PGR301-2018/heroku-pipeline-app.git
      branch: master
      private_key: ((deploy_key_app))

# Replace with your own repository
- name: heroku-pipeline-infra
  type: git
  source:
      uri: git@github.com:PGR301-2018/heroku-pipeline-infra.git
      branch: master
      private_key: ((deploy_key_infra))
